services:
  postgres:
    image: postgres:15
    container_name: e_commerce_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  bot:
    build:
      context: ./bot
    container_name: e_commerce_bot
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./bot:/app
    restart: unless-stopped

volumes:
  pgdata:
