services:
  postgres:
    image: postgres:15
    container_name: e_commerce_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  bot:
    build:
      context: ./bot
    container_name: e_commerce_bot
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./bot/app:/app
      - ./shared:/app/shared
    restart: unless-stopped
  api:
    build:
      context: ./api
    container_name: e_commerce_api
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./api/app:/app
      - ./shared:/app/shared
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
